services:
  - type: web
    name: portfolio-2-0
    env: node
    buildCommand: npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20.10.0
